#!/bin/bash

#PBS -N gamer

#PBS -m abe
#PBS -q workq
#PBS -k n
#PBS -l walltime=720:00:00
#PBS -l nodes=2:ppn=16
##PBS -o stdout
##PBS -e stderr
##PBS -W depend=afterok:JOB_ID
##PBS -W depend=afterany:JOB_ID


if [ "$PBS_ENVIRONMENT" != "PBS_INTERACTIVE" ]; then
   cd $PBS_O_WORKDIR
fi

rm Attributes
python attributes.py  1>>Attributes



## script to restart a simulation automatically if the run failed
## sh auto_restart.sh 1>>stdout 2>>stderr

